package com.example.data.auth

import android.content.Context
import android.content.SharedPreferences
import android.util.Log
import com.example.BuildConfig
import com.google.firebase.FirebaseApp
import com.google.firebase.FirebaseOptions
import com.google.firebase.auth.FirebaseAuth
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

data class FirebaseConfig(
    val webClientId: String = "",
    val apiKey: String = "",
    val projectId: String = "",
    val appId: String = "",
    val isConfigured: Boolean = false,
    val lastUpdated: Long = 0L
)

class FirebaseConfigManager(private val context: Context) {

    private val prefs: SharedPreferences = context.getSharedPreferences("firebase_cloud_config", Context.MODE_PRIVATE)
    private val TAG = "FirebaseConfigManager"

    private val _configState = MutableStateFlow(loadConfig())
    val configState: StateFlow<FirebaseConfig> = _configState.asStateFlow()

    fun loadConfig(): FirebaseConfig {
        var savedClientId = prefs.getString(KEY_WEB_CLIENT_ID, "") ?: ""
        var savedApiKey = prefs.getString(KEY_API_KEY, "") ?: ""
        var savedProjectId = prefs.getString(KEY_PROJECT_ID, "") ?: ""
        var savedAppId = prefs.getString(KEY_APP_ID, "") ?: ""
        val lastUpdated = prefs.getLong(KEY_LAST_UPDATED, 0L)

        // Fallback to BuildConfig if not explicitly stored in prefs
        if (savedClientId.isBlank()) {
            val buildClientId = try { BuildConfig.FIREBASE_WEB_CLIENT_ID } catch (e: Exception) { "" }
            if (buildClientId.isNotBlank() && buildClientId != "MY_FIREBASE_WEB_CLIENT_ID" && buildClientId != "null") {
                savedClientId = buildClientId
            }
        }
        if (savedApiKey.isBlank()) {
            val buildApiKey = try { BuildConfig.FIREBASE_API_KEY } catch (e: Exception) { "" }
            savedApiKey = if (buildApiKey.isNotBlank() && buildApiKey != "MY_FIREBASE_API_KEY" && buildApiKey != "null") {
                buildApiKey
            } else {
                "AIzaSyB5ZcLBCJiEI2aXyH2eLehlxGOjJh7u8kw"
            }
        }
        if (savedProjectId.isBlank()) {
            val buildProjId = try { BuildConfig.FIREBASE_PROJECT_ID } catch (e: Exception) { "" }
            savedProjectId = if (buildProjId.isNotBlank() && buildProjId != "MY_FIREBASE_PROJECT_ID" && buildProjId != "null") {
                buildProjId
            } else {
                "proof-mark"
            }
        }
        if (savedAppId.isBlank()) {
            savedAppId = "1:542599562195:android:84edb719acc96ea9f92526"
        }

        val isCustom = savedClientId.isNotBlank() || savedApiKey.isNotBlank()

        return FirebaseConfig(
            webClientId = savedClientId,
            apiKey = savedApiKey,
            projectId = savedProjectId,
            appId = savedAppId,
            isConfigured = isCustom,
            lastUpdated = lastUpdated
        )
    }

    fun saveConfig(
        webClientId: String,
        apiKey: String = "",
        projectId: String = "",
        appId: String = ""
    ) {
        val cleanClientId = webClientId.trim()
        val cleanApiKey = apiKey.trim()
        val cleanProjectId = projectId.trim()
        val cleanAppId = appId.trim()
        val now = System.currentTimeMillis()

        prefs.edit()
            .putString(KEY_WEB_CLIENT_ID, cleanClientId)
            .putString(KEY_API_KEY, cleanApiKey)
            .putString(KEY_PROJECT_ID, cleanProjectId)
            .putString(KEY_APP_ID, cleanAppId)
            .putLong(KEY_LAST_UPDATED, now)
            .apply()

        _configState.value = FirebaseConfig(
            webClientId = cleanClientId,
            apiKey = cleanApiKey,
            projectId = cleanProjectId,
            appId = cleanAppId,
            isConfigured = cleanClientId.isNotBlank() || cleanApiKey.isNotBlank(),
            lastUpdated = now
        )

        Log.i(TAG, "Saved custom Firebase API configuration.")
    }

    fun resetToDefaults() {
        prefs.edit().clear().apply()
        _configState.value = FirebaseConfig()
        Log.i(TAG, "Reset Firebase API configuration to system defaults.")
    }

    fun getEffectiveWebClientId(): String {
        val custom = _configState.value.webClientId
        if (custom.isNotBlank() && custom != "MY_FIREBASE_WEB_CLIENT_ID") {
            return custom
        }

        // Try reading default_web_client_id from string resources (generated by google-services.json if present)
        try {
            val resId = context.resources.getIdentifier("default_web_client_id", "string", context.packageName)
            if (resId != 0) {
                val resValue = context.getString(resId)
                if (resValue.isNotBlank() && !resValue.startsWith("YOUR_")) {
                    return resValue
                }
            }
        } catch (e: Exception) {
            Log.w(TAG, "Could not resolve default_web_client_id resource: ${e.message}")
        }

        // Fallback default client ID
        return "542599562195-proofmark.apps.googleusercontent.com"
    }

    fun testFirebaseStatus(): Result<String> {
        return try {
            val app = try {
                FirebaseApp.getInstance()
            } catch (e: Exception) {
                null
            }

            val auth = try {
                FirebaseAuth.getInstance()
            } catch (e: Exception) {
                null
            }

            val effectiveClientId = getEffectiveWebClientId()
            val hasCustomKeys = _configState.value.isConfigured

            val statusBuilder = StringBuilder()
            if (auth != null) {
                statusBuilder.append("✓ Firebase Auth service initialized\n")
            } else {
                statusBuilder.append("⚠ Firebase Auth uninitialized\n")
            }

            if (app != null) {
                statusBuilder.append("✓ Firebase App: ${app.name}\n")
                val pid = app.options.projectId
                if (!pid.isNullOrBlank()) {
                    statusBuilder.append("✓ Project ID: $pid\n")
                }
            } else {
                statusBuilder.append("ℹ Running with runtime Credential Manager\n")
            }

            statusBuilder.append("✓ Active Web Client ID: ${effectiveClientId.take(18)}... (${if (hasCustomKeys) "Custom Config" else "Default Standby"})")

            Result.success(statusBuilder.toString())
        } catch (e: Exception) {
            Result.failure(Exception("Firebase Diagnostic error: ${e.localizedMessage ?: e.message}"))
        }
    }

    companion object {
        private const val KEY_WEB_CLIENT_ID = "pref_firebase_web_client_id"
        private const val KEY_API_KEY = "pref_firebase_api_key"
        private const val KEY_PROJECT_ID = "pref_firebase_project_id"
        private const val KEY_APP_ID = "pref_firebase_app_id"
        private const val KEY_LAST_UPDATED = "pref_firebase_last_updated"
    }
}
